//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPFS.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmailContentResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailContentResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KPFS.Web.Resources.EmailContentResource", typeof(EmailContentResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Hi,&lt;/p&gt;
        ///
        ///&lt;p&gt;Please use @Model.LoginOtp to login into KPFS Experience App.
        ///This OTP is valid for 5 minutes.&lt;/p&gt;
        ///
        ///&lt;p&gt;Thanks,&lt;br/&gt;
        ///KPFS EXP&lt;/p&gt;.
        /// </summary>
        public static string LoginOtpEmailBody {
            get {
                return ResourceManager.GetString("LoginOtpEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KPFS EXP | Login.
        /// </summary>
        public static string LoginOtpEmailSubject {
            get {
                return ResourceManager.GetString("LoginOtpEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Hi,&lt;/p&gt;
        ///
        ///&lt;p&gt;Thank you for registering with KPFS Experience App. Please click &lt;a href=&quot;@Model.ConfirmEmailLink&quot;&gt;here&lt;/a&gt; to activate your account.&lt;/p&gt;
        ///
        ///&lt;p&gt;Thanks,&lt;br/&gt;
        ///KPFS EXP&lt;/p&gt;.
        /// </summary>
        public static string UserEmailConfirmationEmailBody {
            get {
                return ResourceManager.GetString("UserEmailConfirmationEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KPFS EXP | Account Activation.
        /// </summary>
        public static string UserEmailConfirmationEmailSubject {
            get {
                return ResourceManager.GetString("UserEmailConfirmationEmailSubject", resourceCulture);
            }
        }
    }
}
